#!/usr/bin/env python3
"""
Build an offline incremental 3D object memory from frame-level 3D observations.

This first version processes observations in frame order and associates each
new 3D observation with existing objects using generic evidence:

  3D bbox overlap + Gaussian point overlap + center distance
  + label similarity + temporal consistency

It intentionally avoids dataset-specific label rules. Label similarity starts
with a small generic string rule and can be overridden by a JSON similarity file
generated by an LLM/embedding stage later.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Any

import numpy as np


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_ROOT = PROJECT_ROOT / "output" / "object_memory"


def read_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def next_available_dir(base_dir: Path, name: str) -> Path:
    candidate = base_dir / name
    if not candidate.exists():
        return candidate
    suffix = 1
    while True:
        candidate = base_dir / f"{name}_{suffix}"
        if not candidate.exists():
            return candidate
        suffix += 1


def make_output_dir(output_root: Path) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return next_available_dir(output_root, f"memory_{timestamp}")


def normalize_label(label: str) -> str:
    label = label.strip().lower().replace("_", " ")
    label = re.sub(r"\s+", " ", label)
    return label


def label_tokens(label: str) -> set[str]:
    tokens = set()
    for token in normalize_label(label).split():
        if not token:
            continue
        tokens.add(token)
        if token.endswith("s") and len(token) > 3:
            tokens.add(token[:-1])
    return tokens


def load_label_similarity(path: Path | None) -> dict[tuple[str, str], float]:
    if path is None:
        return {}
    data = read_json(path)
    pairs: dict[tuple[str, str], float] = {}
    if isinstance(data, dict):
        items = data.get("pairs", data)
        if isinstance(items, dict):
            for key, value in items.items():
                if isinstance(key, str) and "|" in key:
                    left, right = key.split("|", 1)
                    score = float(value)
                    pairs[(normalize_label(left), normalize_label(right))] = score
                    pairs[(normalize_label(right), normalize_label(left))] = score
        elif isinstance(items, list):
            for item in items:
                if not isinstance(item, dict):
                    continue
                left = item.get("label_a") or item.get("left") or item.get("a")
                right = item.get("label_b") or item.get("right") or item.get("b")
                if left is None or right is None:
                    continue
                score = float(item.get("similarity", item.get("score", 0.0)))
                pairs[(normalize_label(str(left)), normalize_label(str(right)))] = score
                pairs[(normalize_label(str(right)), normalize_label(str(left)))] = score
    return pairs


def semantic_similarity(label_a: str, label_b: str, overrides: dict[tuple[str, str], float]) -> float:
    a = normalize_label(label_a)
    b = normalize_label(label_b)
    if (a, b) in overrides:
        return float(np.clip(overrides[(a, b)], 0.0, 1.0))
    if a == b:
        return 1.0
    if a in b or b in a:
        return 0.8
    tokens_a = label_tokens(a)
    tokens_b = label_tokens(b)
    if tokens_a and tokens_b:
        jaccard = len(tokens_a & tokens_b) / len(tokens_a | tokens_b)
        if jaccard > 0:
            return max(0.35, min(0.75, jaccard))
    return 0.2


def as_array(values: Any) -> np.ndarray:
    arr = np.asarray(values, dtype=np.float64)
    if arr.shape != (3,):
        raise ValueError(f"Expected 3-vector, got shape {arr.shape}")
    return arr


def bbox_iou_3d(a_min: np.ndarray, a_max: np.ndarray, b_min: np.ndarray, b_max: np.ndarray) -> float:
    inter_min = np.maximum(a_min, b_min)
    inter_max = np.minimum(a_max, b_max)
    inter_size = np.maximum(inter_max - inter_min, 0.0)
    inter_vol = float(np.prod(inter_size))
    if inter_vol <= 0.0:
        return 0.0
    a_vol = float(np.prod(np.maximum(a_max - a_min, 0.0)))
    b_vol = float(np.prod(np.maximum(b_max - b_min, 0.0)))
    union = a_vol + b_vol - inter_vol
    if union <= 0.0:
        return 0.0
    return inter_vol / union


def point_overlap(obs_points: np.ndarray, obj_points: np.ndarray) -> float:
    if len(obs_points) == 0 or len(obj_points) == 0:
        return 0.0
    inter = np.intersect1d(obs_points, obj_points, assume_unique=False)
    return float(len(inter) / max(min(len(obs_points), len(obj_points)), 1))


def center_distance_score(obs_center: np.ndarray, obj_center: np.ndarray, obs_size: np.ndarray, obj_size: np.ndarray, min_scale: float) -> float:
    distance = float(np.linalg.norm(obs_center - obj_center))
    obs_diag = float(np.linalg.norm(np.maximum(obs_size, 0.0)))
    obj_diag = float(np.linalg.norm(np.maximum(obj_size, 0.0)))
    scale = max((obs_diag + obj_diag) * 0.5, min_scale)
    return math.exp(-distance / scale)


def temporal_score(frame_id: int, last_seen_frame: int | None, window: float) -> float:
    if last_seen_frame is None:
        return 0.0
    gap = max(0, int(frame_id) - int(last_seen_frame))
    if window <= 0:
        return 1.0 if gap == 0 else 0.0
    return math.exp(-gap / window)


def bbox_from_min_max(bbox_min: np.ndarray, bbox_max: np.ndarray) -> dict[str, list[float] | float]:
    size = np.maximum(bbox_max - bbox_min, 0.0)
    center = (bbox_min + bbox_max) * 0.5
    return {
        "center_3d": [round(float(x), 6) for x in center.tolist()],
        "bbox_min": [round(float(x), 6) for x in bbox_min.tolist()],
        "bbox_max": [round(float(x), 6) for x in bbox_max.tolist()],
        "bbox_size": [round(float(x), 6) for x in size.tolist()],
        "bbox_volume": round(float(np.prod(size)), 9),
    }


def make_object(object_index: int, obs: dict[str, Any], obs_points: np.ndarray) -> dict[str, Any]:
    object_id = f"obj_{object_index:06d}"
    label = normalize_label(str(obs["label"]))
    bbox_min = as_array(obs["bbox_min"])
    bbox_max = as_array(obs["bbox_max"])
    frame_id = int(obs["frame_id"])
    object_points = np.unique(obs_points.astype(np.int32))
    geometry = bbox_from_min_max(bbox_min, bbox_max)
    return {
        "object_id": object_id,
        "status": "candidate",
        "canonical_label": label,
        "aliases": [label],
        "label_counts": {label: 1},
        "observation_indices": [int(obs["observation_index"])],
        "observation_ids": [obs["observation_id"]],
        "observed_frames": [frame_id],
        "first_seen_frame": frame_id,
        "last_seen_frame": frame_id,
        "support_frame_count": 1,
        "support_observation_count": 1,
        "point_count": int(len(object_points)),
        "object_point_key": f"{object_id}_points",
        "mean_box_score": float(obs.get("max_box_score") or 0.0),
        "mean_mask_score": float(obs.get("max_mask_score") or 0.0),
        "mean_hit_ratio": float(obs.get("hit_ratio") or 0.0),
        "_point_indices": object_points,
        "_bbox_min_np": bbox_min,
        "_bbox_max_np": bbox_max,
        **geometry,
    }


def update_object(obj: dict[str, Any], obs: dict[str, Any], obs_points: np.ndarray, confirmed_min_frames: int, confirmed_min_observations: int) -> None:
    label = normalize_label(str(obs["label"]))
    frame_id = int(obs["frame_id"])
    obj["observation_indices"].append(int(obs["observation_index"]))
    obj["observation_ids"].append(obs["observation_id"])
    if frame_id not in obj["observed_frames"]:
        obj["observed_frames"].append(frame_id)
        obj["observed_frames"].sort()
    obj["first_seen_frame"] = min(int(obj["first_seen_frame"]), frame_id)
    obj["last_seen_frame"] = max(int(obj["last_seen_frame"]), frame_id)
    obj["support_frame_count"] = len(obj["observed_frames"])
    obj["support_observation_count"] = len(obj["observation_ids"])
    label_counts = Counter(obj.get("label_counts", {}))
    label_counts[label] += 1
    obj["label_counts"] = dict(sorted(label_counts.items(), key=lambda item: (-item[1], item[0])))
    obj["canonical_label"] = next(iter(obj["label_counts"]))
    obj["aliases"] = sorted(obj["label_counts"].keys())

    old_count = max(int(obj["support_observation_count"]) - 1, 1)
    new_count = int(obj["support_observation_count"])
    obj["mean_box_score"] = (float(obj["mean_box_score"]) * old_count + float(obs.get("max_box_score") or 0.0)) / new_count
    obj["mean_mask_score"] = (float(obj["mean_mask_score"]) * old_count + float(obs.get("max_mask_score") or 0.0)) / new_count
    obj["mean_hit_ratio"] = (float(obj["mean_hit_ratio"]) * old_count + float(obs.get("hit_ratio") or 0.0)) / new_count

    bbox_min = np.minimum(obj["_bbox_min_np"], as_array(obs["bbox_min"]))
    bbox_max = np.maximum(obj["_bbox_max_np"], as_array(obs["bbox_max"]))
    obj["_bbox_min_np"] = bbox_min
    obj["_bbox_max_np"] = bbox_max
    obj.update(bbox_from_min_max(bbox_min, bbox_max))

    obj["_point_indices"] = np.union1d(obj["_point_indices"], np.unique(obs_points.astype(np.int32)))
    obj["point_count"] = int(len(obj["_point_indices"]))
    if obj["support_frame_count"] >= confirmed_min_frames or obj["support_observation_count"] >= confirmed_min_observations:
        obj["status"] = "confirmed"


def match_observation(
    obs: dict[str, Any],
    obs_points: np.ndarray,
    objects: list[dict[str, Any]],
    semantic_overrides: dict[tuple[str, str], float],
    weights: dict[str, float],
    min_center_scale: float,
    temporal_window: float,
    min_semantic_similarity: float,
) -> tuple[dict[str, Any] | None, dict[str, Any] | None]:
    if not objects:
        return None, None

    obs_min = as_array(obs["bbox_min"])
    obs_max = as_array(obs["bbox_max"])
    obs_center = as_array(obs["center_3d"])
    obs_size = as_array(obs["bbox_size"])
    frame_id = int(obs["frame_id"])
    label = str(obs["label"])

    best_object = None
    best_score = None
    for obj in objects:
        obj_min = obj["_bbox_min_np"]
        obj_max = obj["_bbox_max_np"]
        obj_center = as_array(obj["center_3d"])
        obj_size = as_array(obj["bbox_size"])
        components = {
            "bbox_iou": bbox_iou_3d(obs_min, obs_max, obj_min, obj_max),
            "point_overlap": point_overlap(obs_points, obj["_point_indices"]),
            "semantic_similarity": semantic_similarity(label, str(obj["canonical_label"]), semantic_overrides),
            "center_distance_score": center_distance_score(obs_center, obj_center, obs_size, obj_size, min_center_scale),
            "temporal_consistency": temporal_score(frame_id, obj.get("last_seen_frame"), temporal_window),
        }
        semantic_eligible = components["semantic_similarity"] >= min_semantic_similarity
        score = sum(weights[name] * components[name] for name in weights)
        if not semantic_eligible:
            score = min(score, min_semantic_similarity - 1e-6)
        detail = {
            "object_id": obj["object_id"],
            "score": round(float(score), 6),
            "components": {key: round(float(value), 6) for key, value in components.items()},
            "semantic_eligible": semantic_eligible,
            "canonical_label": obj["canonical_label"],
            "aliases": obj["aliases"],
            "last_seen_frame": obj.get("last_seen_frame"),
        }
        if best_score is None or score > best_score["score"]:
            best_object = obj
            best_score = detail
    return best_object, best_score


def clean_object_for_json(obj: dict[str, Any]) -> dict[str, Any]:
    hidden = {"_point_indices", "_bbox_min_np", "_bbox_max_np"}
    out = {key: value for key, value in obj.items() if key not in hidden}
    out["mean_box_score"] = round(float(out["mean_box_score"]), 6)
    out["mean_mask_score"] = round(float(out["mean_mask_score"]), 6)
    out["mean_hit_ratio"] = round(float(out["mean_hit_ratio"]), 8)
    return out


def write_matches_csv(path: Path, matches: list[dict[str, Any]]) -> None:
    fieldnames = [
        "frame_id",
        "frame_stem",
        "observation_id",
        "label",
        "action",
        "object_id",
        "score",
        "bbox_iou",
        "point_overlap",
        "semantic_similarity",
        "center_distance_score",
        "temporal_consistency",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for match in matches:
            components = match.get("match", {}).get("components", {}) if isinstance(match.get("match"), dict) else {}
            writer.writerow(
                {
                    "frame_id": match.get("frame_id"),
                    "frame_stem": match.get("frame_stem"),
                    "observation_id": match.get("observation_id"),
                    "label": match.get("label"),
                    "action": match.get("action"),
                    "object_id": match.get("object_id"),
                    "score": match.get("match", {}).get("score") if isinstance(match.get("match"), dict) else None,
                    "bbox_iou": components.get("bbox_iou"),
                    "point_overlap": components.get("point_overlap"),
                    "semantic_similarity": components.get("semantic_similarity"),
                    "center_distance_score": components.get("center_distance_score"),
                    "temporal_consistency": components.get("temporal_consistency"),
                }
            )


def parse_weights(value: str) -> dict[str, float]:
    defaults = {
        "bbox_iou": 0.25,
        "point_overlap": 0.35,
        "semantic_similarity": 0.20,
        "center_distance_score": 0.15,
        "temporal_consistency": 0.05,
    }
    if not value.strip():
        return defaults
    weights = dict(defaults)
    for part in value.split(","):
        if not part.strip():
            continue
        key, raw = part.split("=", 1)
        key = key.strip()
        if key not in weights:
            raise ValueError(f"Unknown weight key: {key}")
        weights[key] = float(raw)
    total = sum(weights.values())
    if total <= 0:
        raise ValueError("Weight sum must be positive")
    return {key: value / total for key, value in weights.items()}


def main() -> None:
    parser = argparse.ArgumentParser(description="Build offline incremental object memory from 3D observations")
    parser.add_argument("--frame_3d_observations_json", type=Path, required=True)
    parser.add_argument("--hits_npz", type=Path, default=None)
    parser.add_argument("--output_root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--match_threshold", type=float, default=0.55)
    parser.add_argument("--confirmed_min_frames", type=int, default=2)
    parser.add_argument("--confirmed_min_observations", type=int, default=3)
    parser.add_argument("--min_center_scale", type=float, default=0.5)
    parser.add_argument("--temporal_window", type=float, default=60.0)
    parser.add_argument("--min_semantic_similarity", type=float, default=0.35)
    parser.add_argument("--weights", type=str, default="")
    parser.add_argument("--label_similarity_json", type=Path, default=None)
    parser.add_argument("--max_observations", type=int, default=None)
    args = parser.parse_args()

    data = read_json(args.frame_3d_observations_json)
    observations = data.get("observations") if isinstance(data, dict) else None
    if not isinstance(observations, list):
        raise ValueError(f"Expected observations list in {args.frame_3d_observations_json}")
    observations = sorted(observations, key=lambda obs: (int(obs["frame_id"]), int(obs["observation_index"])))
    if args.max_observations is not None and args.max_observations > 0:
        observations = observations[: args.max_observations]

    hits_npz_path = args.hits_npz
    if hits_npz_path is None:
        hits_npz = data.get("metadata", {}).get("hits_npz")
        if not hits_npz:
            raise ValueError("Pass --hits_npz or provide metadata.hits_npz in frame_3d_observations_json")
        hits_npz_path = Path(str(hits_npz))
    hits = np.load(hits_npz_path)
    weights = parse_weights(args.weights)
    semantic_overrides = load_label_similarity(args.label_similarity_json)

    output_dir = make_output_dir(args.output_root)
    output_dir.mkdir(parents=True, exist_ok=True)

    objects: list[dict[str, Any]] = []
    matches: list[dict[str, Any]] = []
    scene_delta: list[dict[str, Any]] = []
    frame_events: dict[int, list[dict[str, Any]]] = {}

    for obs in observations:
        hit_key = str(obs.get("hit_key"))
        if hit_key not in hits:
            match_record = {
                "frame_id": obs.get("frame_id"),
                "frame_stem": obs.get("frame_stem"),
                "observation_id": obs.get("observation_id"),
                "label": obs.get("label"),
                "action": "skipped_missing_hit_points",
                "object_id": None,
                "match": None,
            }
            matches.append(match_record)
            continue
        obs_points = np.unique(np.asarray(hits[hit_key], dtype=np.int32))
        best_object, best_match = match_observation(
            obs=obs,
            obs_points=obs_points,
            objects=objects,
            semantic_overrides=semantic_overrides,
            weights=weights,
            min_center_scale=args.min_center_scale,
            temporal_window=args.temporal_window,
            min_semantic_similarity=args.min_semantic_similarity,
        )
        frame_id = int(obs["frame_id"])
        frame_events.setdefault(frame_id, [])
        if best_object is not None and best_match is not None and float(best_match["score"]) >= args.match_threshold:
            previous_status = best_object["status"]
            update_object(best_object, obs, obs_points, args.confirmed_min_frames, args.confirmed_min_observations)
            action = "matched_existing"
            event = {
                "type": action,
                "frame_id": frame_id,
                "frame_stem": obs.get("frame_stem"),
                "observation_id": obs.get("observation_id"),
                "label": obs.get("label"),
                "object_id": best_object["object_id"],
                "canonical_label": best_object["canonical_label"],
                "match": best_match,
            }
            if previous_status != "confirmed" and best_object["status"] == "confirmed":
                event["status_update"] = "confirmed_object"
            frame_events[frame_id].append(event)
            matches.append(
                {
                    "frame_id": frame_id,
                    "frame_stem": obs.get("frame_stem"),
                    "observation_id": obs.get("observation_id"),
                    "label": obs.get("label"),
                    "action": action,
                    "object_id": best_object["object_id"],
                    "match": best_match,
                }
            )
        else:
            obj = make_object(len(objects), obs, obs_points)
            objects.append(obj)
            action = "new_candidate"
            event = {
                "type": action,
                "frame_id": frame_id,
                "frame_stem": obs.get("frame_stem"),
                "observation_id": obs.get("observation_id"),
                "label": obs.get("label"),
                "object_id": obj["object_id"],
                "canonical_label": obj["canonical_label"],
                "best_match": best_match,
            }
            frame_events[frame_id].append(event)
            matches.append(
                {
                    "frame_id": frame_id,
                    "frame_stem": obs.get("frame_stem"),
                    "observation_id": obs.get("observation_id"),
                    "label": obs.get("label"),
                    "action": action,
                    "object_id": obj["object_id"],
                    "match": best_match,
                }
            )

    object_arrays = {obj["object_point_key"]: obj["_point_indices"].astype(np.int32) for obj in objects}
    points_path = output_dir / "object_memory_points.npz"
    np.savez_compressed(points_path, **object_arrays)
    clean_objects = [clean_object_for_json(obj) for obj in objects]

    for frame_id in sorted(frame_events):
        events = frame_events[frame_id]
        scene_delta.append(
            {
                "frame_id": frame_id,
                "frame_stem": events[0].get("frame_stem") if events else None,
                "events": events,
                "event_counts": dict(Counter(event["type"] for event in events)),
            }
        )

    status_counts = Counter(obj["status"] for obj in clean_objects)
    label_counts = Counter(obj["canonical_label"] for obj in clean_objects)
    summary = {
        "input_observation_count": len(observations),
        "object_count": len(clean_objects),
        "status_counts": dict(sorted(status_counts.items())),
        "canonical_label_counts": dict(label_counts.most_common()),
        "match_threshold": args.match_threshold,
        "confirmed_min_frames": args.confirmed_min_frames,
        "confirmed_min_observations": args.confirmed_min_observations,
        "min_semantic_similarity": args.min_semantic_similarity,
        "weights": weights,
    }
    payload = {
        "format": "object_memory_v1",
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "metadata": {
            "frame_3d_observations_json": str(args.frame_3d_observations_json),
            "hits_npz": str(hits_npz_path),
            "object_memory_points_npz": str(points_path),
            "label_similarity_json": str(args.label_similarity_json) if args.label_similarity_json else None,
        },
        "summary": summary,
        "objects": clean_objects,
    }
    write_json(output_dir / "object_memory.json", payload)
    write_json(output_dir / "object_observation_matches.json", {"matches": matches})
    write_json(output_dir / "scene_delta_log.json", {"frames": scene_delta})
    write_matches_csv(output_dir / "object_observation_matches.csv", matches)

    lines = [
        "Object memory update summary",
        "",
        f"input_observations: {len(observations)}",
        f"objects: {len(clean_objects)}",
        f"status_counts: {dict(sorted(status_counts.items()))}",
        f"top_labels: {label_counts.most_common(20)}",
        f"object_memory_points_npz: {points_path}",
        f"output: {output_dir}",
    ]
    (output_dir / "summary.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"[input_observations] {len(observations)}")
    print(f"[objects] {len(clean_objects)}")
    print(f"[status_counts] {dict(sorted(status_counts.items()))}")
    print(f"[top_labels] {label_counts.most_common(10)}")
    print(f"[points_npz] {points_path}")
    print(f"[output] {output_dir}")


if __name__ == "__main__":
    main()
